project:
  type: website
  output-dir: docs

website:
  title: "Celine Park"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: My R projects!
      - href: portfolio.qmd
        text: My Reports!
    
     
    

format:
  html:
    theme: 
      - mystyles.scss
    mainfont: Times New Roman
    toc: true
    page-layout: full

editor: visual

