project:
  type: website
  output-dir: docs

website:
  title: "celinepark.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: My Portfolio!
      - href: about.qmd
        text: About
    

format:
  html:
    theme: 
      - mystyles.scss
    mainfont: Times New Roman
    toc: true
    page-layout: full

editor: visual

